### ISSUE TITLE
Switching human movement type to amphibious does not work

### ISSUE THREAD

**Issue by SaintWacko** [joseasoler/Pathfinding-Framework#110]
**Describe the bug**

Setting humans to amphibious does not seem to work.

**HugsLib log**

https://gist.github.com/HugsLibRecordKeeper/dd41412eefe63ea2b373bd8d3a9db453

**To Reproduce**

1. At the main menu, go into mod settings -> Pathfinding Framework and change humans to amphibious
2. Draft a pawn
3. Try to send them into deep water

**Expected behavior**

If humans are set to amphibious, they should be able to swim in deep water

**Comment by joseasoler** [comment]
Thank you for the report!

I have just confirmed this issue, it will be fixed in the next release.

**Comment by joseasoler** [comment]
The issue has been fixed and the new 0.3.7 release will be pushed to Steam when I get access to a better internet connection.
