### ISSUE TITLE
Swimming creatures occasionally lock up

### ISSUE THREAD

**Issue by SaintWacko** [joseasoler/Pathfinding-Framework#111]
**Describe the bug**

Swimming creatures occasionally lock up and begin spamming the log with NullReferenceExceptions.

**HugsLib log**

https://gist.github.com/HugsLibRecordKeeper/65279d49777637b40d2296ca4f741ba3

**Screenshots**

<img width="1219" alt="Screenshot 2023-12-07 at 10 15 03" src="https://github.com/joseasoler/Pathfinding-Framework/assets/10342141/bdaf8cf2-15c5-428c-86f3-4d0965aa849a">

**Additional context**

I have not found a specific set of circumstances that causes this. It's usually just a single creature somewhere on the map. What prompted this report, however, was it happening to an entire group of manhunting manta rays. It happened shortly after they crossed onto a patch of shallow ocean water, but I don't know if that's related. Unfortunately the only solution I've found is to use dev mode and destroy the affected creature(s), as otherwise the log spam slows the game to a crawl.

**Comment by SaintWacko** [comment]
Hm. This actually just happened with a caravan pawn, too. Guess it's not just swimming creatures.

**Comment by SaintWacko** [comment]
Oh, although it looks like the patch to fix changing human movement hit, so maybe it is the swimming pathfinding that's broken

**Comment by SaintWacko** [comment]
Oh, more interesting information. Saving and reloading fixed the pawn.

**Comment by joseasoler** [comment]
Thank you for the report!

I believe this issue is related to how regions are handled in RimWorld, and how Pathfinding Framework modifies them to implement its features. It is likely that PF is generating one or more regions incorrectly, and this causes the issue you are experiencing.

Regions are modified in-game after constructing bridges and buildings, so maybe one of those changes triggered the PF bug. Regions are fully regenerated after loading a game and the code is slightly different, that could explain why the issue went away.

I would need to know more about the incorrect region that is causing this issue. Could you run the "Error Report Information" debug action, generate another HugsLib log, and send it to me?

![image](https://github.com/joseasoler/Pathfinding-Framework/assets/3092211/a830acb6-7fe2-45a9-91d7-f9dd32c22b95)

**Comment by SaintWacko** [comment]
I assume I need to do that while I have a currently locked up creature?

**Comment by SaintWacko** [comment]
Oh, good timing! Just got one: https://gist.github.com/HugsLibRecordKeeper/29d73a738afe173b62d998f9590a28a5

**Comment by joseasoler** [comment]
Thank you! Unfortunately that log does not include the error report information. Maybe there are so many previous errors that the log stopped accepting more text. You could try pausing the game as soon as you get the first red error and then using the error report information immediatly after that.

Another option would be to manually check the map for anything weird. You could use the "Draw region / draw region links" and "Region inspector" tools described in this page (https://github.com/joseasoler/Pathfinding-Framework/wiki/Testing-and-troubleshooting#draw-region--draw-region-links) to check the regions in the map, and try to find if any of them has errors.

Meanwhile I have started a new game on an island map to see if I get any errors.

**Comment by SaintWacko** [comment]
Hm, I just got the lock up again, but when I run the Error Report Information, it seems to only generate information about one of my colonists

**Comment by SaintWacko** [comment]
No idea if this one'll do any good: https://gist.github.com/HugsLibRecordKeeper/0c90d8f5b08d17b247508b0bb851b378

I tried the region inspector and stuff, and nothing jumped out at me as an error, but I may not know what I'm looking for.

**Comment by SaintWacko** [comment]
Hm, and this time saving and reloading isn't fixing it

**Comment by joseasoler** [comment]
Thank you for the additional information. If the error report is only giving you a single line talking about "last reachability" then it is not finding the errors I was hoping to find.

I will try to reproduce this by generating random island maps and spawning multiple aquatic manhunter groups. With more information it might be possible to find out where PF is making this pathfinding error.

**Comment by joseasoler** [comment]
Unfortunately I have not been able to reproduce this issue after multiple tries. Since I am using a minimal modlist, I wonder if it is some kind of mod conflict.

**Comment by joseasoler** [comment]
This issue has been taken out of the plans for 0.4.0 as it cannot be reproduced at the moment. I will keep it open for a while in case it resurfaces.

**Comment by joseasoler** [comment]
Terrain mods that might have something to do with the issue:

There is some fake water tiles from Alpha Props - Parks and Gardens -> https://steamcommunity.com/sharedfiles/filedetails/?id=3146268928
Nanites are from Buildable Terrain -> https://steamcommunity.com/sharedfiles/filedetails/?id=1420979918
And the star in square is from [JF] Geometric Floors -> https://steamcommunity.com/sharedfiles/filedetails/?id=2863525144
